name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff mypy
          pip install pytest

      - name: Run Ruff (linter)
        run: ruff check .

      - name: Run Mypy (type checking)
        run: mypy .
        
      - name: Run Unit Tests
        run: pytest tests/test_translator.py

      - name: Run Golden Tests
        run: |
          find tests -name '*.s' | while IFS= read -r s_file; do
            echo "Compiling $s_file"
            python translator.py "$s_file" "${s_file%.s}.bin"
            if [ -f "$(dirname "$s_file")/golden.log" ]; then
               diff "${s_file%.s}.log" "$(dirname "$s_file")/golden.log" || exit 1
            fi
          done